apiVersion: apps/v1
kind: Deployment
metadata:
  name: bedrock-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bedrock-app
  template:
    metadata:
      labels:
        app: bedrock-app
    spec:
      containers:
        - name: bedrock-app
          image: yaswanthmitta/multiapp-bedrock-app:d7c046062b0ee9e698eae4effb32851bbc59a164
          ports:
            - containerPort: 5005
          envFrom:
            - secretRef:
                name: bedrock-secrets
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5005
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5005
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "256Mi"
              cpu: "200m"
